# Generated by Django 2.0.5 on 2018-06-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='id',
        ),
        migrations.AddField(
            model_name='user_info',
            name='uid',
            field=models.IntegerField(default=10000, primary_key=True, serialize=False),
        ),
    ]
